#!/bin/bash

name=$(jq -r '.name' data.json)
height_dm=$(jq -r '.height' data.json)
weight_hg=$(jq -r '.weight' data.json)

type_raw=$(jq -r '.types[0].type.name' data.json)
type=$(echo "$type_raw" | sed 's/.*/\u&/')

formatted_height=$(echo "$height_dm" | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(echo "$weight_hg" | awk '{printf "%d", $1 / 10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
